TASK: "csnet-L-x2"

GPU: 0

MODEL:
  ARCH: "csnet"
  BASIC_SPLIT: [0.5,0.5]

DATA:
  DIR: "/kaggle/input/duts-saliency-detection-dataset/DUTS-TE"
  PRETRAIN: ''
  BATCH_SIZE: 24
  WORKERS: 0
  IMAGE_H: 224
  IMAGE_W: 224
  RESUME: ""

VAL:
  DIR: "/kaggle/input/duts-saliency-detection-dataset/DUTS-TE"

TEST:
  DATASET_PATH: '/kaggle/input/duts-saliency-detection-dataset'
  DATASETS: ['DUTS-TE']
  INTERVAL: 5
  ENABLE: False
  IMAGE_H: 224
  IMAGE_W: 224
  TESTALL: False
  CHECKPOINT:  "checkpoints/csnet-L-x2/csnet-L-x2.pth.tar"
  MODEL_CONFIG: "checkpoints/csnet-L-x2/csnet-L-x2.bin"
